version: 5

common:
  train_log_path: ./data/manufacturing/manufacturing_simod_cleaned.csv
  log_ids:
    case: "case_id"
    activity: "activity"
    resource: "resource"
    start_time: "start_time"
    end_time: "end_time"

preprocessing:
  enable_time_concurrency_threshold: 0.9
  multitasking: false

control_flow:
  optimization_metric: two_gram_distance
  mining_algorithm: sm2

  num_iterations: 1
  num_evaluations_per_iteration: 1

  epsilon: 0.4
  eta: 0.5

  replace_or_joins: [false]
  prioritize_parallelism: [false]
  discover_branch_rules: false

resource_model:
  optimization_metric: circadian_emd

  num_iterations: 1
  num_evaluations_per_iteration: 1

  discover_prioritization_rules: false
  discover_batching_rules: false

  resource_profiles:
    discovery_type: differentiated # undifferentiated

extraneous_activity_delays:
  discovery_method: eclipse-aware
  num_iterations: 1
